<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapas [
<!ELEMENT etapas (etapa)+>
<!ELEMENT etapa (origen, destino, f-inicio, f-fin, m-transporte, foto, anecdota)>
<!ATTLIST etapa id ID #REQUIRED>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT f-inicio (#PCDATA)>
<!ELEMENT f-fin (#PCDATA)>
<!ELEMENT m-transporte (#PCDATA)>
<!ELEMENT foto ANY>
<!ELEMENT anecdota (#PCDATA)>
]>

<etapas>
  <etapa id="uno">
      <origen>Pekin</origen>
      <destino>Budapest</destino>
      <f-inicio>14/06/2020</f-inicio>
      <f-fin>20/06/2020</f-fin>
      <m-transporte>Tren, coche y avión</m-transporte>
      <foto>1.jpg</foto>
      <anecdota>Salimos desde Pekin con un tren hasta llegar a la ciudad de Shaanxi, allí podremos encontrar a los famosos guerreros de terracota
        en esa parada nos hospedamos en un hotel de la zona, nos despertamos con un gran desayuno. Partimos sobre las 12 en coche y fuimos día tras día recorriendo
        gran parte del país chino, tras unos cuántos días de viaje por fin llegamos a la ciudad de Lhasa para coger un avión y ponernos rumbo a Budapest, una
        esplendida ciudad europea.</anecdota>
  </etapa>
  <etapa id="dos">
      <origen>Budapest</origen>
      <destino>Miami</destino>
      <f-inicio>sda</f-inicio>
      <f-fin>ads</f-fin>
      <m-transporte>ad</m-transporte>
      <foto>ads.jpg</foto>
      <anecdota></anecdota>
  </etapa>
  <etapa id="tres">
      <origen>Miami</origen>
      <destino>Los Angeles</destino>
      <f-inicio></f-inicio>
      <f-fin></f-fin>
      <m-transporte></m-transporte>
      <foto></foto>
      <anecdota></anecdota>
  </etapa>
  <etapa id="cuatro">
      <origen>Los Angeles</origen>
      <destino></destino>
      <f-inicio></f-inicio>
      <f-fin></f-fin>
      <m-transporte></m-transporte>
      <foto></foto>
      <anecdota></anecdota>
  </etapa>
</etapas>